/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AltitudePanel.java
 *
 * Created on 21-09-2012, 19:31:24
 */
package fidolib.ui;

import fidolib.data.Constants;
import java.awt.Graphics;
import java.util.Calendar;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Steen
 */
public class AltitudePanel extends javax.swing.JPanel {

    private int spotSize = 1;
    private int maxSpotSize = 14;
    private long lastSpotPaint = 0;
    private long deltaSpotPaint = 50;
    private Calendar calendar = Calendar.getInstance();
    private int xAxesBorder = 60; // Pixels
    private int yAxesBorder = 60; // Pixels
    private int xAxesScale = 10; // Km
    private int yAxesScale = 20; // Km
    private int lineWidth = 3;
    private int ticksLineWidth = 2;
    private int xTicks = 10;
    private int yTicks = 20;
    /**
     * Timer delay
     */
    private int delay = 0;
    /**
     * Timer period for GUI updates
     */
    private long period = Constants.deltaT_GUI;
    /**
     * The timer it self
     */
    private Timer timer = new Timer();

    /** Creates new form AltPanel */
    public AltitudePanel() {
        initComponents();


        // Set and start the timer
        timer.scheduleAtFixedRate(new TimerTask() {

            public void run() {
                repaint();
            }
        }, delay, period);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);

        paintCoorSys(g);
        paintRocket(g);

    }

    public void paintRocket(Graphics g) {
        g.setColor(Constants.textColor);
        calendar = Calendar.getInstance();
        if ((calendar.getTimeInMillis() - lastSpotPaint) > deltaSpotPaint) {
            lastSpotPaint = calendar.getTimeInMillis();
            spotSize = (spotSize + 2) % maxSpotSize;

        }
        g.setColor(Constants.rocketColor);
        g.fillOval(20 - (spotSize / 2), 20 - (spotSize / 2), spotSize, spotSize);
    }

    /**
     * Paint the coordinate system
     * @param g 
     */
    public void paintCoorSys(Graphics g) {

        int width = this.getWidth();
        int height = this.getHeight();
        g.setColor(Constants.backGroundColor);
        g.fillRect(0, 0, width, height);
        g.setColor(Constants.textColor);

        g.fillRect(xAxesBorder, height - yAxesBorder, width - xAxesBorder * 2, lineWidth);
        g.fillRect(xAxesBorder, yAxesBorder, lineWidth, height - xAxesBorder * 2);

        
        int sLength = 0;
        int xTicksPixels = (int)((width - xAxesBorder * 2) / xTicks );
        for (int i = 0; i <= xAxesScale; i += ((int)(1.0 / ((double) xTicks/ (double)xAxesScale)))) {
            g.fillRect(xAxesBorder + (i * xTicksPixels / (xAxesScale / xTicks)), height - yAxesBorder, ticksLineWidth, ticksLineWidth * 4);
            sLength = g.getFontMetrics().stringWidth("" + i);
            g.drawString("" + i, xAxesBorder + (i * xTicksPixels / (xAxesScale / xTicks)) - sLength / 4, height - yAxesBorder / 2);
        }
        String downRangeStr = "Down range (Km)";
        sLength = g.getFontMetrics().stringWidth(downRangeStr);
        g.drawString(downRangeStr, width / 2 - sLength / 2, height - yAxesBorder / 4);
        
        
        int yTicksPixels = (int)((height - yAxesBorder * 2) / yTicks );
        for (int i = 0; i <= yAxesScale; i += ((int)(1.0 / ((double) yTicks/ (double)yAxesScale)))) {
            g.fillRect(xAxesBorder - ticksLineWidth * 4 , height - yAxesBorder - (i * yTicksPixels / (yAxesScale / yTicks)), ticksLineWidth * 4, ticksLineWidth);
            sLength = g.getFontMetrics().stringWidth("" + i);
            g.drawString("" + i, xAxesBorder /3 * 2 - sLength , height - yAxesBorder - (i * yTicksPixels / (yAxesScale / yTicks)) - sLength / 4);
        }
        String altitudeRangeStr = "Altitude (Km)";
        sLength = g.getFontMetrics().stringWidth(altitudeRangeStr);
        g.drawString(altitudeRangeStr, xAxesBorder - sLength / 2, yAxesBorder / 3 * 2);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
