/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DegreeFormatDialog.java
 *
 * Created on 28-04-2012, 16:25:24
 */
package fidolib.ui;

import fidolib.data.Constants;

/**
 *
 * @author Steen
 */
public class DegreeFormatDialog extends javax.swing.JDialog {

    /** Creates new form DegreeFormatDialog */
    public DegreeFormatDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Format of degrees");
        this.decimalDegreejRadioButton1.setText("Decimal degrees (i.e 55.062643 N)" + Constants.degreeChar + ")");
        this.decimalMinutesjRadioButton2.setText("Degrees, decimal minutes (i.e. 55" + Constants.degreeChar + "  3.758')");
        this.degreeMinSecjRadioButton1.setText("Degrees, minutes, seconds (i.e. 55" + Constants.degreeChar + " 03' 45.47'')");
        if (Constants.DegreeFormat.DECIMAL == Constants.degreeFormat)
        {
            decimalDegreejRadioButton1.setSelected(true);
        }
        else if (Constants.DegreeFormat.DECIMALMINUTE == Constants.degreeFormat)
        {
            decimalMinutesjRadioButton2.setSelected(true);
        }
        else if (Constants.DegreeFormat.DECIMALMINSEC == Constants.degreeFormat)
        {
            degreeMinSecjRadioButton1.setSelected(true);
        }
        
        degreeButtonGroup1.add(decimalDegreejRadioButton1);
        degreeButtonGroup1.add(decimalMinutesjRadioButton2);
        degreeButtonGroup1.add(degreeMinSecjRadioButton1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        degreeButtonGroup1 = new javax.swing.ButtonGroup();
        OKjButton1 = new javax.swing.JButton();
        radioButtonjPanel1 = new javax.swing.JPanel();
        decimalDegreejRadioButton1 = new javax.swing.JRadioButton();
        decimalMinutesjRadioButton2 = new javax.swing.JRadioButton();
        degreeMinSecjRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(DegreeFormatDialog.class);
        OKjButton1.setText(resourceMap.getString("OKjButton1.text")); // NOI18N
        OKjButton1.setName("OKjButton1"); // NOI18N
        OKjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKjButton1ActionPerformed(evt);
            }
        });

        radioButtonjPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("radioButtonjPanel1.border.title"))); // NOI18N
        radioButtonjPanel1.setName("radioButtonjPanel1"); // NOI18N

        decimalDegreejRadioButton1.setText(resourceMap.getString("decimalDegreejRadioButton1.text")); // NOI18N
        decimalDegreejRadioButton1.setName("decimalDegreejRadioButton1"); // NOI18N
        decimalDegreejRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalDegreejRadioButton1ActionPerformed(evt);
            }
        });

        decimalMinutesjRadioButton2.setText(resourceMap.getString("decimalMinutesjRadioButton2.text")); // NOI18N
        decimalMinutesjRadioButton2.setName("decimalMinutesjRadioButton2"); // NOI18N
        decimalMinutesjRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalMinutesjRadioButton2ActionPerformed(evt);
            }
        });

        degreeMinSecjRadioButton1.setText(resourceMap.getString("degreeMinSecjRadioButton1.text")); // NOI18N
        degreeMinSecjRadioButton1.setName("degreeMinSecjRadioButton1"); // NOI18N
        degreeMinSecjRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeMinSecjRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout radioButtonjPanel1Layout = new javax.swing.GroupLayout(radioButtonjPanel1);
        radioButtonjPanel1.setLayout(radioButtonjPanel1Layout);
        radioButtonjPanel1Layout.setHorizontalGroup(
            radioButtonjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioButtonjPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(radioButtonjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(degreeMinSecjRadioButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(decimalMinutesjRadioButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(decimalDegreejRadioButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        radioButtonjPanel1Layout.setVerticalGroup(
            radioButtonjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioButtonjPanel1Layout.createSequentialGroup()
                .addComponent(decimalDegreejRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decimalMinutesjRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(degreeMinSecjRadioButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(OKjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(radioButtonjPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioButtonjPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OKjButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKjButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_OKjButton1ActionPerformed

    private void decimalDegreejRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalDegreejRadioButton1ActionPerformed
        
        Constants.degreeFormat = Constants.DegreeFormat.DECIMAL;
        
    }//GEN-LAST:event_decimalDegreejRadioButton1ActionPerformed

    private void decimalMinutesjRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalMinutesjRadioButton2ActionPerformed
        
        Constants.degreeFormat = Constants.DegreeFormat.DECIMALMINUTE;
    }//GEN-LAST:event_decimalMinutesjRadioButton2ActionPerformed

    private void degreeMinSecjRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeMinSecjRadioButton1ActionPerformed
       Constants.degreeFormat = Constants.DegreeFormat.DECIMALMINSEC;
    }//GEN-LAST:event_degreeMinSecjRadioButton1ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKjButton1;
    private javax.swing.JRadioButton decimalDegreejRadioButton1;
    private javax.swing.JRadioButton decimalMinutesjRadioButton2;
    private javax.swing.ButtonGroup degreeButtonGroup1;
    private javax.swing.JRadioButton degreeMinSecjRadioButton1;
    private javax.swing.JPanel radioButtonjPanel1;
    // End of variables declaration//GEN-END:variables
}
