/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fidolib.ui;

import fidolib.data.Constants;

/**
 *
 * @author Steen
 */
public class DegreeFormatDialog extends javax.swing.JDialog {

    /**
     * Creates new form DegreeFormatDialog
     */
    public DegreeFormatDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Format of degrees");
        this.decimalDegreejRadioButton1.setText("Decimal degrees (i.e 55.062643 N)" + Constants.degreeChar + ")");
        this.decimalMinutesjRadioButton1.setText("Degrees, decimal minutes (i.e. 55" + Constants.degreeChar + "  3.758')");
        this.degreeMinSecjRadioButton1.setText("Degrees, minutes, seconds (i.e. 55" + Constants.degreeChar + " 03' 45.47'')");
        if (Constants.DegreeFormat.DECIMAL == Constants.degreeFormat)
        {
            decimalDegreejRadioButton1.setSelected(true);
        }
        else if (Constants.DegreeFormat.DECIMALMINUTE == Constants.degreeFormat)
        {
            decimalMinutesjRadioButton1.setSelected(true);
        }
        else if (Constants.DegreeFormat.DECIMALMINSEC == Constants.degreeFormat)
        {
            degreeMinSecjRadioButton1.setSelected(true);
        }
        
        degreeButtonGroup1.add(decimalDegreejRadioButton1);
        degreeButtonGroup1.add(decimalMinutesjRadioButton1);
        degreeButtonGroup1.add(degreeMinSecjRadioButton1);
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        degreeButtonGroup1 = new javax.swing.ButtonGroup();
        radioButtenjPanel1 = new javax.swing.JPanel();
        decimalDegreejRadioButton1 = new javax.swing.JRadioButton();
        decimalMinutesjRadioButton1 = new javax.swing.JRadioButton();
        degreeMinSecjRadioButton1 = new javax.swing.JRadioButton();
        okjButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        radioButtenjPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Degree Format"));

        decimalDegreejRadioButton1.setText("jRadioButton1");
        decimalDegreejRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalDegreejRadioButton1ActionPerformed(evt);
            }
        });

        decimalMinutesjRadioButton1.setText("jRadioButton1");
        decimalMinutesjRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalMinutesjRadioButton1ActionPerformed(evt);
            }
        });

        degreeMinSecjRadioButton1.setText("jRadioButton1");
        degreeMinSecjRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeMinSecjRadioButton1ActionPerformed(evt);
            }
        });

        okjButton1.setText("OK");
        okjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout radioButtenjPanel1Layout = new javax.swing.GroupLayout(radioButtenjPanel1);
        radioButtenjPanel1.setLayout(radioButtenjPanel1Layout);
        radioButtenjPanel1Layout.setHorizontalGroup(
            radioButtenjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioButtenjPanel1Layout.createSequentialGroup()
                .addGroup(radioButtenjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(decimalDegreejRadioButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(degreeMinSecjRadioButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(decimalMinutesjRadioButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(radioButtenjPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(okjButton1)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        radioButtenjPanel1Layout.setVerticalGroup(
            radioButtenjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioButtenjPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(decimalDegreejRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decimalMinutesjRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(degreeMinSecjRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okjButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioButtenjPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioButtenjPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okjButton1ActionPerformed
         this.dispose();
    }//GEN-LAST:event_okjButton1ActionPerformed

    private void decimalDegreejRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalDegreejRadioButton1ActionPerformed
        Constants.degreeFormat = Constants.DegreeFormat.DECIMAL;
    }//GEN-LAST:event_decimalDegreejRadioButton1ActionPerformed

    private void decimalMinutesjRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalMinutesjRadioButton1ActionPerformed
         Constants.degreeFormat = Constants.DegreeFormat.DECIMALMINUTE;
    }//GEN-LAST:event_decimalMinutesjRadioButton1ActionPerformed

    private void degreeMinSecjRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeMinSecjRadioButton1ActionPerformed
         Constants.degreeFormat = Constants.DegreeFormat.DECIMALMINSEC;
    }//GEN-LAST:event_degreeMinSecjRadioButton1ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DegreeFormatDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DegreeFormatDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DegreeFormatDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DegreeFormatDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DegreeFormatDialog dialog = new DegreeFormatDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton decimalDegreejRadioButton1;
    private javax.swing.JRadioButton decimalMinutesjRadioButton1;
    private javax.swing.ButtonGroup degreeButtonGroup1;
    private javax.swing.JRadioButton degreeMinSecjRadioButton1;
    private javax.swing.JButton okjButton1;
    private javax.swing.JPanel radioButtenjPanel1;
    // End of variables declaration//GEN-END:variables
}
